name: restoran
description: Sebuah aplikasi review restoran.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  flutter_screenutil: ^3.1.1
  connectivity: ^3.0.6
  provider: ^6.0.0
  dio: ^4.0.0
  moor_flutter: ^4.0.0
  shared_preferences: ^2.0.6
  android_alarm_manager: ^2.0.2
  intl: ^0.17.0
  flutter_local_notifications: ^8.1.1+1
  rxdart: ^0.27.1

dev_dependencies:
  build_runner: ^2.1.1
  moor_generator:
  mockito: ^5.0.15
  bloc_test: ^8.1.0
  test: ^1.17.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/